navbar:
  blog_title: 'SPD7'
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill', name: 'Home' }
    - { key: 'archives', link: '/archives/', icon: 'iconfont icon-archive-fill', name: 'Archives' }
    - { key: 'categories', link: '/categories/', icon: 'iconfont icon-folder-fill', name: 'Categories' }
    - { key: 'tags', link: '/tags/', icon: 'iconfont icon-tags-fill', name: 'Tags' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: 'About' }
    - { key: 'cv', link: '/cv.html', icon: 'iconfont icon-download-fill', name: 'Download CV' }

about:
  banner_img_height: 0
  avatar: ''
  name: 'Rakan'
  intro: 'IT Engineer · Riyadh'
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/spade-sketch7', tip: 'GitHub' }
